更新到 LFS v7.3

diff --git a/bootscripts/lfs/lib/services/ipv4-static b/bootscripts/lfs/lib/services/ipv4-static
--- a/bootscripts/lfs/lib/services/ipv4-static
+++ b/bootscripts/lfs/lib/services/ipv4-static
@@ -42,37 +42,31 @@ fi
 
 case "${2}" in
    up)
-      if [ "$(ip addr show ${1} | grep ${IP})" == "" ]; then
-         log_info_msg2 "\n" # Terminate the previous message
+      if [ "$(ip addr show ${1} 2>/dev/null | grep ${IP}/)" = "" ]; then
+         
+         # Cosmetic output not needed for multiple services
+         if ! $(echo ${SERVICE} | grep -q " "); then 
+           log_info_msg2 "\n" # Terminate the previous message
+         fi
+         
          log_info_msg "Adding IPv4 address ${IP} to the ${1} interface..."
          ip addr add ${args} dev ${1}
          evaluate_retval
-
-         if [ -n "${GATEWAY}" ]; then
-            if ip route | grep -q default; then
-               log_warning_msg "\nGateway already setup; skipping."
-            else
-               log_info_msg "Setting up default gateway..."
-               ip route add default via ${GATEWAY} dev ${1}
-               evaluate_retval
-             fi
-         fi
       else
-         msg="Cannot add IPv4 address ${IP} to ${1}.  Already present."
-         log_warning_msg "$msg"
+         log_warning_msg "Cannot add IPv4 address ${IP} to ${1}.  Already present."
       fi
    ;;
 
    down)
-      if [ "$(ip addr show ${1} | grep ${IP})" != "" ]; then
+      if [ "$(ip addr show ${1} 2>/dev/null | grep ${IP}/)" != "" ]; then
          log_info_msg "Removing IPv4 address ${IP} from the ${1} interface..."
          ip addr del ${args} dev ${1}
          evaluate_retval
       fi
 
       if [ -n "${GATEWAY}" ]; then
-         # Only remove the gateway if ther are no remaining ipv4 addresses
-         if [ "$(ip addr show ${1} | grep 'inet ')" != "" ]; then
+         # Only remove the gateway if there are no remaining ipv4 addresses
+         if [ "$(ip addr show ${1} 2>/dev/null | grep 'inet ')" != "" ]; then
             log_info_msg "Removing default gateway..."
             ip route del default
             evaluate_retval
